tomcat:
  ajp:
   protocol: AJP/1.3
   port: 8001

spring:
  profiles:
    active: debug  
  redis:
    host: http://127.0.0.1
    port: 6379
---
spring:
  profiles: debug
  datasource:
    username: ENC(xWFcYX6tLaatvLHPLRqQdw==)
    password: ENC(mvIZcmcn3LVBkX6K79sJjQM4d4lf1REp)
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(H1c7dGvEBNs8GyFm5jalM8JrWf6dQEIxZgYntsvv84hLOF8z5vWLlz4N091FM32RFkmAZuPTJakRcOI2LzGXGtsPY2veb7r0XhxhPmo+TeOtWloP/kMEWXliaUWfscgZhfTyy20rKfpoznn2cGCkyL8NtzsjWIdcZt5ulMOc4CJIE/Ct1ZAHzW62xxwrAc6E0EgXSbt7+NnIJAdev9JI90HXJ92OCnaocE2trcAWrVancBUmusyadIw+U0Fvs8FgM/jnatMpIsCo20YLbWoguf510QzagcrTtV2ngTudu2CO3nJiMPP+rOYTqF/lDBSjhZXPOQY1Th7FfHjX/7wbd4T2oUYpcLZt)    
  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.OracleDialect
        temp.use_jdbc_metadata_defaults: false

---
spring:
  profiles: release
  datasource:
    username: ENC(GJpq3/JvgLuxJUuA7eO8Xw==)
    password: ENC(216nUHOMgIm5rH4bIPtq9SO/hi5nPJeP)
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(D0G3DuJQLJz/L7KmYDqu0fRnzwR+dtOX8OBgZcd3yH9ZRqB4KjNWCyCygDFPybrJqVakWDtizAf2+X478yMCdj8Q9l3qYVQlSLbOt/kGHwR5Fhtg1O5M41knjTxBEcycKYhRQwzRuApAQN0ZDFVsR63wXJs4UdzVJES4Xi7xqY3QTgVVgEFNq9sxrVVegy1Dx8rdllhqWnLexOO0j8bipaeETbGoE8e2wCh+iohRv3k6U0wDtAQ6Wz4Vk1WF5nECXq4hC98fZQPIopObNpuWyaFvCAGoKvtbVKHAZY6UcS9pPBo/uqktgW1c9P1rgm/Y1vYumiASPCPc3gJ72SPjhql23tqzWG298DHeQYBo0Ng=)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        temp.use_jdbc_metadata_defaults: false
---
security: 
  oauth2:
    client:
      auto-approve-scopes: ".*"  
    resource:
      jwt:
        key-uri: http://localhost:8080/oauth/token
jasypt:
  encryptor:
    bean: jasyptStringEncryptor        