tomcat:
  ajp:
   protocol: AJP/1.3
   port: 8001

spring:
  profiles:
    active: debug  
  redis:
    host: http://127.0.0.1
    port: 6379
---
spring:
  profiles: debug
  datasource:
    username: ENC(xWFcYX6tLaatvLHPLRqQdw==)
    password: ENC(Srjs5uZo6VNC1mPWosz0zEOEvGus+2TL)
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(QxrL8m9CTbXzWEPTBkw8r9WiUR2rJMvWw0lAvf7ut1oLZEsEgFlo4YshyCSlhpjfYz5AzxZVP068+w8Plx/vTec1Fo2vuwSylb2KxtZ8n1Q=)
    
  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.OracleDialect
        temp.use_jdbc_metadata_defaults: false

---
spring:
  profiles: release
  datasource:
    username: ENC(GJpq3/JvgLuxJUuA7eO8Xw==)
    password: ENC(oKorkaek31JEbkqb5ARaqVp1ckeXnAjN)
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(OG0w89rlc/otDmjnsT95g5hVxj25BSmoXHZFsHd0ywVamk9mS/a+fawdDP4rUEM0xVYMVVrgI4o25XRvuDxfmQ==)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        temp.use_jdbc_metadata_defaults: false
---
security: 
  oauth2:
    client:
      auto-approve-scopes: ".*"  
    resource:
      jwt:
        key-uri: http://localhost:8080/oauth/token
jasypt:
  encryptor:
    bean: jasyptStringEncryptor        