spring:
  profiles:
    active: debug  
  redis:
    host: http://127.0.0.1
    port: 6379
---
spring:
  profiles: debug
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: tmtl5467
    
  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false

---
spring:
  profiles: release
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: tmtl5467

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
---
security: 
  oauth2:
    client:
      auto-approve-scopes: ".*"
    authorization:
      token-key-access: isAuthenticated()
      check-token-access: isAuthenticated()
    resource:
      jwt:
        key-uri: http://localhost:8080/oauth/token